/**
 * 应急指挥会议历史还原模式数据结构
 * 基于《战役设定：江城危急 —— 武汉2024"暴力梅"防御战》
 * 严格遵循《镜头剧本》中的8个关键点位和运镜规划
 */

// 历史事件类型
export type HistoricalEventType = 
  | 'narration'
  | 'alert'
  | 'report'
  | 'meeting_start'
  | 'attendance'
  | 'briefing'
  | 'order'
  | 'response'
  | 'escalation'
  | 'critical_event'
  | 'camera_move';

// 单个历史事件
export interface HistoricalEvent {
  id: string;
  time: string;
  type: HistoricalEventType;
  speaker: string;
  speakerRole?: string;
  speakerDepartment?: string;
  title?: string;
  content: string;
  location?: {
    lat: number;
    lng: number;
    label?: string;
    zoom?: number;
  };
  cameraConfig?: {
    center: { lat: number; lng: number };
    zoom: number;
    duration?: number;
    action?: 'flyTo' | 'panTo' | 'easeOut';
  };
  isUrgent?: boolean;
  isHighlight?: boolean;
  emotion?: 'calm' | 'urgent' | 'worried' | 'confident' | 'concerned';
  soundEffect?: string;
  icon?: string;
  attendees?: string[];
  round?: number;
  subEvents?: HistoricalEvent[];
}

export interface HistoricalScript {
  id: string;
  caseId: string;
  name: string;
  description: string;
  phases: ScriptPhase[];
}

export interface ScriptPhase {
  id: string;
  name: string;
  description: string;
  round: number;
  responseLevel: string;
  startTime: string;
  endTime: string;
  events: HistoricalEvent[];
  mapConfig?: {
    center: { lat: number; lng: number };
    zoom: number;
  };
  cameraSteps?: CameraStep[];
  backgroundNarration?: string;
}

export interface CameraStep {
  step: number;
  description: string;
  target: string;
  center: { lat: number; lng: number };
  zoom: number;
  action: 'flyTo' | 'panTo' | 'easeOut';
  duration?: number;
  overlay?: string;
}

export interface ReplayState {
  currentPhaseIndex: number;
  currentEventIndex: number;
  isPlaying: boolean;
  playbackSpeed: number;
  autoAdvance: boolean;
  selectedEventId: string | null;
}

export function getEventColor(type: HistoricalEventType): string {
  const colors: Record<HistoricalEventType, string> = {
    narration: '#94a3b8',
    alert: '#ef4444',
    report: '#f59e0b',
    meeting_start: '#8b5cf6',
    attendance: '#06b6d4',
    briefing: '#3b82f6',
    order: '#ec4899',
    response: '#10b981',
    escalation: '#dc2626',
    critical_event: '#991b1b',
    camera_move: '#6366f1',
  };
  return colors[type] || '#94a3b8';
}

export function getEventIcon(type: HistoricalEventType): string {
  const icons: Record<HistoricalEventType, string> = {
    narration: 'book-open',
    alert: 'alert-triangle',
    report: 'upload',
    meeting_start: 'users',
    attendance: 'user-check',
    briefing: 'message-square',
    order: 'clipboard-list',
    response: 'check-circle',
    escalation: 'trending-up',
    critical_event: 'alert-octagon',
    camera_move: 'video',
  };
  return icons[type] || 'circle';
}

export function eventHasLocation(event: HistoricalEvent): boolean {
  return !!event.location && !!event.location.lat && !!event.location.lng;
}

export function getEventRecommendedZoom(event: HistoricalEvent): number | undefined {
  return event.location?.zoom || event.cameraConfig?.zoom;
}

export const wuhanWaterloggingHistoricalScript: HistoricalScript = {
  id: 'wuhan-waterlogging-replay-v2',
  caseId: 'wuhan-waterlogging-2024',
  name: '江城危急 -- 武汉2024"暴力梅"防御战',
  description: '基于真实历史数据的应急指挥推演，从IV级响应到I级响应的全过程还原',
  phases: [
    {
      id: 'phase-0-prologue',
      name: '序章：风暴前夜',
      description: '展示武汉全市地理格局，长江汉水交汇，入梅前夕',
      round: 0,
      responseLevel: '',
      startTime: '06-18 00:00',
      endTime: '06-18 23:59',
      cameraSteps: [{
        step: 1,
        description: '全市概览，长江汉水交汇',
        target: '武汉市政府',
        center: { lat: 30.599554, lng: 114.305393 },
        zoom: 10.5,
        action: 'easeOut',
        duration: 3000,
        overlay: '动态降雨云图层',
      }],
      mapConfig: {
        center: { lat: 30.599554, lng: 114.305393 },
        zoom: 10.5,
      },
      backgroundNarration: '2024年6月中旬，武汉正式入梅。气象预测显示，今年"梅雨"强度可能突破历史极值...',
      events: [
        {
          id: 'event-0-1',
          time: '06-18 08:00',
          type: 'narration',
          speaker: '系统旁白',
          title: '入梅公告',
          content: [
            '[2024年6月18日 . 武汉]',
            '',
            '📍 **武汉市气象局** 发布重要天气报告：',
            '',
            '🌧 **武汉今日正式入梅**',
            '',
            '根据监测，西太平洋副热带高压已北抬至华南沿海，南方暖湿气流开始活跃。预计未来27天，我市将迎来历史罕见的"暴力梅"天气过程。',
            '',
            '**气候背景**：',
            '• 往年平均梅雨期：23天',
            '• 今年预测：27天+（超长梅雨）',
            '• 累计降雨量：可能突破800毫米',
            '',
            '⚠ **风险提示**：',
            '• 长江流域已进入主汛期',
            '• 上游来水量持续增加',
            '• 城市排水系统将面临极限考验',
            '',
            '🎯 全市各部门请密切关注天气变化，做好防汛准备！',
          ].join('\n'),
          location: { lat: 30.599554, lng: 114.305393, label: '武汉市政府', zoom: 10.5 },
          cameraConfig: { center: { lat: 30.599554, lng: 114.305393 }, zoom: 10.5, duration: 3000, action: 'easeOut' },
          isHighlight: true,
          round: 0,
        },
        {
          id: 'event-0-2',
          time: '06-18 12:00',
          type: 'narration',
          speaker: '系统旁白',
          title: '城市地理格局',
          content: [
            '[武汉城市地理特征]',
            '',
            '🗺 **两江交汇，三镇鼎立**',
            '',
            '武汉地处长江与汉江交汇处，独特的地理位置决定了其防汛复杂性：',
            '',
            '**核心区域**：',
            '• 🏛 **汉口**（江北）：商业中心，地势相对较低',
            '• 🏢 **武昌**（江南）：文教中心，老城区较多',
            '• 🏭 **汉阳**（江南西部）：工业基地',
            '',
            '**防汛重点**：',
            '• 📍 **龙王庙险段**：两江交汇处，水流湍急',
            '• 📍 **竹叶山立交**：经典易涝点，交通要道',
            '• 📍 **武昌老城区**：老旧社区，排水能力弱',
            '',
            '**基础设施**：',
            '• 🏥 同济医院：汉口核心医疗资源',
            '• 🚉 武汉站/汉口站/武昌站：三大铁路枢纽',
            '• 🛣 二环线/三环线：城市快速路网',
            '',
            '本次推演将以**武汉市政府**为指挥中枢，围绕上述重点区域展开...',
          ].join('\n'),
          isHighlight: false,
          round: 0,
        },
      ],
    },
    {
      id: 'phase-1-level4',
      name: '第一回合：梅雨初袭',
      description: '暴雨初降，启动IV级响应，监测与预置',
      round: 1,
      responseLevel: 'IV级（蓝色/黄色预警）',
      startTime: '06-20 14:00',
      endTime: '06-20 22:00',
      cameraSteps: [{
        step: 1,
        description: '聚焦指挥中枢',
        target: '武汉市政府',
        center: { lat: 30.599554, lng: 114.305393 },
        zoom: 16,
        action: 'flyTo',
        duration: 2000,
      }, {
        step: 2,
        description: '巡查易涝点',
        target: '竹叶山立交',
        center: { lat: 30.618765, lng: 114.293456 },
        zoom: 15,
        action: 'panTo',
        duration: 1500,
        overlay: '半径500米蓝色积水预警圈',
      }],
      mapConfig: { center: { lat: 30.599554, lng: 114.305393 }, zoom: 16 },
      backgroundNarration: '入梅第3天，初期雨量逐渐增加，部分低洼地段开始出现积水...',
      events: [
        {
          id: 'event-1-1',
          time: '14:00',
          type: 'camera_move',
          speaker: '镜头控制',
          title: '镜头推进至指挥中心',
          content: [
            '🎬 **镜头动作**：',
            '',
            '从序章全市概览（Zoom 10.5）-> 快速平滑推进至市政府（Zoom 16）',
            '',
            '📍 **目标位置**：武汉市政府',
            '📐 **坐标**：[114.305393, 30.599554]',
            '🔍 **缩放**：16（高亮市政府图标）',
            '',
            '✨ **画面效果**：聚焦指挥中枢，准备接收灾情报告',
          ].join('\n'),
          location: { lat: 30.599554, lng: 114.305393, label: '武汉市政府', zoom: 16 },
          cameraConfig: { center: { lat: 30.599554, lng: 114.305393 }, zoom: 16, duration: 2000, action: 'flyTo' },
          round: 1,
        },
        {
          id: 'event-1-2',
          time: '14:15',
          type: 'alert',
          speaker: '市气象局值班员 小李',
          speakerRole: 'weather-bureau',
          speakerDepartment: '市气象局',
          title: '蓝色预警发布',
          content: [
            '[14:15] 🔵 **蓝色预警发布**',
            '',
            '📢 **气象局值班员 小李** 紧急报告：',
            '',
            '> "市长！气象局监测数据显示：',
            '>',
            '> 🌧 **当前实况**：',
            '> • 过去24小时累计降雨量：52毫米',
            '> • 最大小时雨强：18毫米/小时',
            '> • 预计未来24小时还将有50-80毫米降水',
            '>',
            '> ⚠ **根据《市防汛抗旱应急预案》，现发布暴雨蓝色预警！**',
            '>',
            '> 📋 **建议措施**：',
            '> • 各单位加强值班值守',
            '> • 排查排水设施运行状况',
            '> • 低洼区域设置警示标志',
            '>',
            '> 请指示！"',
          ].join('\n'),
          location: { lat: 30.5995, lng: 114.2925, label: '市气象局' },
          isUrgent: true,
          emotion: 'urgent',
          soundEffect: 'alert_blue',
          round: 1,
        },
      ],
    },
    {
      id: 'phase-2-level3',
      name: '第二回合：暴雨升级',
      description: '暴雨升级为黄色预警，启动III级响应',
      round: 2,
      responseLevel: 'III级（黄色预警）',
      startTime: '06-21 16:00',
      endTime: '06-21 19:00',
      cameraSteps: [{
        step: 1,
        description: '飞入积水核心区',
        target: '竹叶山立交',
        center: { lat: 30.618765, lng: 114.293356 },
        zoom: 16,
        action: 'flyTo',
        duration: 2000,
        overlay: '半径800米蓝色积水扩散圈',
      }, {
        step: 2,
        description: '平移至江堤险段',
        target: '龙王庙险段',
        center: { lat: 30.579125, lng: 114.291172 },
        zoom: 15,
        action: 'panTo',
        duration: 1500,
        overlay: '长江水位超警红色警戒线',
      }],
      mapConfig: { center: { lat: 30.618765, lng: 114.293356 }, zoom: 16 },
      backgroundNarration: '入梅第4天，暴雨持续升级，多个主干道积水深度超过30cm，长江水位超警戒...',
      events: [
        {
          id: 'event-2-1',
          time: '16:00',
          type: 'camera_move',
          speaker: '镜头控制',
          title: '镜头飞入竹叶山立交积水区',
          content: [
            '🎬 **镜头动作**：',
            '',
            '从市政府指挥中枢 -> 高速飞入竹叶山立交（Zoom 16）',
            '',
            '📍 **目标位置**：竹叶山立交（汉口经典易涝点）',
            '📐 **坐标**：[114.293356, 30.618765]',
            '🔍 **缩放**：16（放大积水区域）',
            '',
            '🌊 **画面效果**：积水蓝色半透明覆盖层 + 车辆涉水动画',
          ].join('\n'),
          location: { lat: 30.618765, lng: 114.293356, label: '竹叶山立交', zoom: 16 },
          cameraConfig: { center: { lat: 30.618765, lng: 114.293356 }, zoom: 16, duration: 2000, action: 'flyTo' },
          round: 2,
        },
        {
          id: 'event-2-2',
          time: '16:15',
          type: 'alert',
          speaker: '市气象局值班员 小李',
          speakerRole: 'weather-bureau',
          speakerDepartment: '市气象局',
          title: '暴雨黄色预警升级',
          content: [
            '[16:15] 🟡 **黄色预警升级**',
            '',
            '📢 **气象局值班员 小李** 紧急报告：',
            '',
            '> "市长！暴雨持续增强：',
            '>',
            '> 🌧 **当前实况**：',
            '> • 过去6小时累计降雨量：85毫米',
            '> • 最大小时雨强：35毫米/小时',
            '> • 预计未来6小时还将有60-100毫米降水',
            '>',
            '> ⚠ **升级发布暴雨黄色预警！**',
            '>',
            '> 📋 **建议措施**：',
            '> • 建议启动III级响应',
            '> • 对积水路段实施交通管制',
            '> • 低洼区域组织人员转移',
            '>',
            '> 请指示！"',
          ].join('\n'),
          location: { lat: 30.5995, lng: 114.2925, label: '市气象局' },
          isUrgent: true,
          emotion: 'urgent',
          soundEffect: 'alert_yellow',
          round: 2,
        },
        {
          id: 'event-2-3',
          time: '16:30',
          type: 'report',
          speaker: '市城管局值班员 老张',
          speakerRole: 'urban-management',
          speakerDepartment: '市城管局',
          title: '道路积水情况汇报',
          content: [
            '[16:30] 🌊 **道路积水报告**',
            '',
            '📢 **城管局值班员 老张** 汇报：',
            '',
            '> "市长！城区道路巡查发现：',
            '>',
            '> 🚧 **积水路段**：',
            '> • 竹叶山立交：积水35cm，车辆通行受阻',
            '> • 发展大道：积水28cm，慢速通行',
            '> • 建设大道：积水22cm，尚可通行',
            '> • 汉西路下穿通道：积水40cm，已封闭',
            '>',
            '> 🚿 **排水设施状态**：',
            '> • 全市12座泵站全部开机',
            '> • 排涝能力达300立方米/秒',
            '> • 但降雨量已超过排水设计标准',
            '>',
            '> ⚠ 建议对积水超30cm路段实施交通管制！"',
          ].join('\n'),
          location: { lat: 30.618765, lng: 114.293356, label: '竹叶山立交积水区' },
          isUrgent: true,
          emotion: 'worried',
          round: 2,
        },
        {
          id: 'event-2-4',
          time: '17:00',
          type: 'report',
          speaker: '市交警支队 王队',
          speakerRole: 'traffic-bureau',
          speakerDepartment: '市交警支队',
          title: '交通管制方案',
          content: [
            '[17:00] 🚦 **交通管控报告**',
            '',
            '📢 **交警支队 王队** 汇报：',
            '',
            '> "市长！根据当前积水情况，建议：',
            '>',
            '> 🛑 **封控路段**：',
            '> • 竹叶山立交全向封闭',
            '> • 汉西路下穿通道封闭',
            '> • 发展大道（新华路-常青路段）限行',
            '>',
            '> 🚔 **警力部署**：',
            '> • 已出动警力200人',
            '> • 设置绕行指示牌45处',
            '> • 拖车待命15台',
            '>',
            '> 📱 **信息发布**：',
            '> • 通过交通广播、微博发布绕行提示',
            '> • 与高德/百度地图同步封路信息',
            '>',
            '> 请批准实施交通管制方案！"',
          ].join('\n'),
          location: { lat: 30.613271, lng: 114.288172, label: '市交警支队' },
          isUrgent: true,
          round: 2,
        },
        {
          id: 'event-2-5',
          time: '17:30',
          type: 'order',
          speaker: '市应急管理局 张副局长',
          speakerRole: 'emergency-bureau',
          speakerDepartment: '市应急管理局',
          title: 'III级响应启动令',
          content: [
            '[17:30] 🔶 **III级响应启动**',
            '',
            '📢 **市应急管理局 张副局长** 签发：',
            '',
            '> "根据《市防汛抗旱应急预案》，现启动III级应急响应：',
            '>',
            '> 📋 **响应措施**：',
            '> • 各成员单位按职责到岗值班',
            '> • 对积水超30cm路段实施交通管制',
            '> • 低洼区域居民做好转移准备',
            '> • 开放临时安置点，保障基本生活物资',
            '> • 医疗救援队进入待命状态',
            '>',
            '> 🏗 **工程调度**：',
            '> • 全力开启排涝泵站',
            '> • 加强堤防巡查，每小时报告一次',
            '>',
            '> 📞 指挥部24小时值班电话已开通"',
          ].join('\n'),
          location: { lat: 30.5872, lng: 114.2985, label: '市应急指挥中心', zoom: 16 },
          isUrgent: true,
          emotion: 'concerned',
          round: 2,
        },
        {
          id: 'event-2-6',
          time: '18:00',
          type: 'camera_move',
          speaker: '镜头控制',
          title: '镜头平移至龙王庙险段',
          content: [
            '🎬 **镜头动作**：',
            '',
            '从竹叶山立交 -> 平滑横移至龙王庙险段（Zoom 15）',
            '',
            '📍 **目标位置**：龙王庙险段（汉江与长江交汇处）',
            '📐 **坐标**：[114.291172, 30.579125]',
            '🔍 **缩放**：15',
            '',
            '🌊 **画面效果**：长江水位超警红色标记 + 水流湍急动画',
            '',
            '⚠ **AI参谋提示**：长江水位已超警戒，龙王庙是历史险段，需加强巡查！',
          ].join('\n'),
          location: { lat: 30.579125, lng: 114.291172, label: '龙王庙险段', zoom: 15 },
          cameraConfig: { center: { lat: 30.579125, lng: 114.291172 }, zoom: 15, duration: 1500, action: 'panTo' },
          round: 2,
        },
      ],
    },
    {
      id: 'phase-3-level2',
      name: '第三回合：暴雨巅峰',
      description: '暴雨达到峰值，启动II级橙色预警',
      round: 3,
      responseLevel: 'II级（橙色预警）',
      startTime: '06-21 19:00',
      endTime: '06-21 22:00',
      cameraSteps: [{
        step: 1,
        description: '飞入老城区',
        target: '武昌老城区',
        center: { lat: 30.5406, lng: 114.3027 },
        zoom: 16,
        action: 'flyTo',
        duration: 2000,
        overlay: '老旧社区积水红色警报',
      }, {
        step: 2,
        description: '平移至安置点',
        target: '洪山体育馆',
        center: { lat: 30.5194, lng: 114.3378 },
        zoom: 15,
        action: 'panTo',
        duration: 1500,
        overlay: '避难所人流量热力图',
      }],
      mapConfig: { center: { lat: 30.5406, lng: 114.3027 }, zoom: 16 },
      backgroundNarration: '入梅第4天傍晚，暴雨达到峰值，2小时降雨量超100毫米，10条主干道同时断交...',
      events: [
        {
          id: 'event-3-1',
          time: '19:00',
          type: 'camera_move',
          speaker: '镜头控制',
          title: '镜头飞入武昌老城区',
          content: [
            '🎬 **镜头动作**：',
            '',
            '从龙王庙 -> 高速飞越长江至武昌老城区（Zoom 16）',
            '',
            '📍 **目标位置**：武昌老城区（市三医院附近）',
            '📐 **坐标**：[114.3027, 30.5406]',
            '🔍 **缩放**：16（老旧社区积水倒灌）',
            '',
            '🏚 **画面效果**：老旧社区积水红色警报 + 居民被困求救信号',
          ].join('\n'),
          location: { lat: 30.5406, lng: 114.3027, label: '武昌老城区', zoom: 16 },
          cameraConfig: { center: { lat: 30.5406, lng: 114.3027 }, zoom: 16, duration: 2000, action: 'flyTo' },
          round: 3,
        },
        {
          id: 'event-3-2',
          time: '19:15',
          type: 'alert',
          speaker: '市气象局值班员 小李',
          speakerRole: 'weather-bureau',
          speakerDepartment: '市气象局',
          title: '橙色预警发布',
          content: [
            '[19:15] 🟠 **橙色预警发布**',
            '',
            '📢 **气象局值班员 小李** 紧急报告：',
            '',
            '> "市长！暴雨已达到历史极值：',
            '>',
            '> 🌧 **当前实况**：',
            '> • 过去12小时累计降雨量：180毫米',
            '> • 最大小时雨强：55毫米/小时',
            '> • 已突破50年一遇降水强度',
            '>',
            '> ⚠ **升级发布暴雨橙色预警！**',
            '>',
            '> 🌊 **长江水位**：',
            '> • 汉口站水位：27.30米（警戒27.30米）',
            '> • 预计还将上涨0.5-1.0米',
            '>',
            '> 📋 **建议启动II级响应！**',
          ].join('\n'),
          location: { lat: 30.5995, lng: 114.2925, label: '市气象局' },
          isUrgent: true,
          emotion: 'urgent',
          soundEffect: 'alert_orange',
          round: 3,
        },
        {
          id: 'event-3-3',
          time: '19:30',
          type: 'meeting_start',
          speaker: '市长 周先旺',
          speakerRole: 'mayor',
          speakerDepartment: '市人民政府',
          title: '紧急召开I级指挥部会议',
          content: [
            '[19:30] 🚨 **紧急指挥部会议**',
            '',
            '📢 **市长 周先旺** 紧急召集：',
            '',
            '> "各成员单位注意！',
            '>',
            '> 当前全市已进入防汛紧急状态！',
            '>',
            '> 📊 **当前态势**：',
            '> • 10条主干道断交超过3小时',
            '> • 竹叶山立交积水达60cm',
            '> • 武昌多处老旧社区一楼进水',
            '> • 长江水位已超警戒',
            '>',
            '> 🎯 **会议议题**：',
            '> 1. 是否升级为II级响应？',
            '> 2. 是否请求省级支援？',
            '> 3. 是否启动大面积人员转移？',
            '>',
            '> 请各单位按顺序汇报当前情况！"',
            '',
            '⚠ **AI参谋提示**：此时应立即启动II级响应，并做好全面升级I级响应的准备。老城区居民转移是第一优先级！',
          ].join('\n'),
          location: { lat: 30.5872, lng: 114.2985, label: '市应急指挥中心', zoom: 17 },
          cameraConfig: { center: { lat: 30.5872, lng: 114.2985 }, zoom: 17, duration: 2000, action: 'flyTo' },
          isUrgent: true,
          emotion: 'concerned',
          attendees: ['市长', '应急管理局', '水务局', '气象局', '交警支队', '卫健委', '城管局'],
          round: 3,
        },
        {
          id: 'event-3-4',
          time: '19:45',
          type: 'briefing',
          speaker: '市水务局 陈总工',
          speakerRole: 'water-bureau',
          speakerDepartment: '市水务局',
          title: '水利汛情汇报',
          content: [
            '[19:45] 🌊 **水务局汛情通报**',
            '',
            '📢 **水务局 陈总工** 汇报：',
            '',
            '> "市长！水利汛情严峻：',
            '>',
            '> 🏞 **长江汉口站**：',
            '> • 当前水位27.30m（警戒27.30m）',
            '> • 流量：55000立方米/秒',
            '> • 预计洪峰24小时内到达',
            '>',
            '> 🌉 **汉江**：',
            '> • 新沟站水位：28.50m（超警戒0.5m）',
            '> • 流速较快，冲刷严重',
            '>',
            '> 🏗 **堤防巡查**：',
            '> • 龙王庙险段每小时巡查一次',
            '> • 未发现管涌、渗漏等险情',
            '> • 但水位持续上涨压力巨大',
            '>',
            '> ⚠ 建议启动II级响应，加强堤防防守！"',
          ].join('\n'),
          location: { lat: 30.579125, lng: 114.291172, label: '龙王庙险段' },
          isUrgent: true,
          emotion: 'worried',
          round: 3,
        },
        {
          id: 'event-3-5',
          time: '20:00',
          type: 'report',
          speaker: '市卫健委 刘主任',
          speakerRole: 'health-bureau',
          speakerDepartment: '市卫健委',
          title: '医疗救援汇报',
          content: [
            '[20:00] 🏥 **医疗救援报告**',
            '',
            '📢 **卫健委 刘主任** 汇报：',
            '',
            '> "市长！医疗救援情况如下：',
            '>',
            '> 🚑 **伤员统计**：',
            '> • 累计接诊受伤群众156人',
            '> • 其中重伤12人（已转同济、协和）',
            '> • 轻伤已就近在社区卫生中心处理',
            '>',
            '> 🏥 **医院状态**：',
            '> • 同济医院：正常运行，已加开应急床位',
            '> • 协和医院：正常运行，救护车待命',
            '> • 市中心医院：一楼进水，部分科室停诊',
            '>',
            '> 💊 **物资储备**：',
            '> • 急救药品1000份已到位',
            '> • 防疫物资500套已分发',
            '> • 饮水消毒片20000片已调拨',
            '>',
            '> ⚠ 建议增派心理援助和防疫力量！"',
          ].join('\n'),
          location: { lat: 30.5796, lng: 114.2599, label: '同济医院' },
          isUrgent: false,
          round: 3,
        },
        {
          id: 'event-3-6',
          time: '20:30',
          type: 'order',
          speaker: '市长 周先旺',
          speakerRole: 'mayor',
          speakerDepartment: '市人民政府',
          title: '签署II级响应令',
          content: [
            '[20:30] 🟠 **II级响应启动令**',
            '',
            '📢 **市长 周先旺** 签发命令：',
            '',
            '> "根据《市防汛抗旱应急预案》，现启动II级应急响应！',
            '>',
            '> 📋 **核心指令**：',
            '> 1. 全市进入防汛紧急状态',
            '> 2. 老城区一楼居民立即转移至洪山体育馆安置点',
            '> 3. 全市中小学、幼儿园停课',
            '> 4. 地铁地面段停运，地下段加强抽排',
            '> 5. 请求省级防汛抗旱指挥部支援',
            '>',
            '> 🚨 **最高优先级**：保障人民群众生命安全！',
            '>',
            '> 各单位立即行动，不得有误！"',
          ].join('\n'),
          location: { lat: 30.5872, lng: 114.2985, label: '市应急指挥中心', zoom: 17 },
          cameraConfig: { center: { lat: 30.5872, lng: 114.2985 }, zoom: 17, duration: 1000, action: 'flyTo' },
          isUrgent: true,
          emotion: 'confident',
          round: 3,
        },
        {
          id: 'event-3-7',
          time: '21:00',
          type: 'camera_move',
          speaker: '镜头控制',
          title: '镜头平移至洪山体育馆避难所',
          content: [
            '🎬 **镜头动作**：',
            '',
            '从武昌老城区 -> 平移至洪山体育馆避难所（Zoom 15）',
            '',
            '📍 **目标位置**：洪山体育馆（可容纳5000人的临时安置点）',
            '📐 **坐标**：[114.3378, 30.5194]',
            '🔍 **缩放**：15',
            '',
            '🏟 **画面效果**：避难所人流量热力图 + 救援物资转运动画',
          ].join('\n'),
          location: { lat: 30.5194, lng: 114.3378, label: '洪山体育馆安置点', zoom: 15 },
          cameraConfig: { center: { lat: 30.5194, lng: 114.3378 }, zoom: 15, duration: 1500, action: 'panTo' },
          round: 3,
        },
      ],
    },
    {
      id: 'phase-4-level1',
      name: '第四回合：全城告急',
      description: '暴雨破极值，启动I级红色预警，请求国家级支援',
      round: 4,
      responseLevel: 'I级（红色预警）',
      startTime: '06-21 22:00',
      endTime: '06-22 06:00',
      cameraSteps: [{
        step: 1,
        description: '飞入交通枢纽',
        target: '武汉站',
        center: { lat: 30.6067, lng: 114.4243 },
        zoom: 16,
        action: 'flyTo',
        duration: 2000,
        overlay: '铁路停运红色标识',
      }, {
        step: 2,
        description: '拉远至机场',
        target: '天河机场',
        center: { lat: 30.7737, lng: 114.2211 },
        zoom: 13,
        action: 'panTo',
        duration: 2000,
        overlay: '航班大面积延误橙色标识',
      }, {
        step: 3,
        description: '全市俯瞰总结',
        target: '武汉市政府',
        center: { lat: 30.599554, lng: 114.305393 },
        zoom: 10.5,
        action: 'easeOut',
        duration: 3000,
        overlay: '全市积水红色覆盖 + 救援力量蓝色散点',
      }],
      mapConfig: { center: { lat: 30.6067, lng: 114.4243 }, zoom: 16 },
      backgroundNarration: '暴雨突破历史极值，12小时累计降雨量突破300毫米，全市进入I级响应...',
      events: [
        {
          id: 'event-4-1',
          time: '22:00',
          type: 'camera_move',
          speaker: '镜头控制',
          title: '镜头飞入武汉站',
          content: [
            '🎬 **镜头动作**：',
            '',
            '从洪山体育馆 -> 高速飞入武汉站（Zoom 16）',
            '',
            '📍 **目标位置**：武汉火车站（高铁枢纽）',
            '📐 **坐标**：[114.4243, 30.6067]',
            '🔍 **缩放**：16',
            '',
            '🚄 **画面效果**：站前广场积水 + 列车停运红色标识 + 滞留旅客',
          ].join('\n'),
          location: { lat: 30.6067, lng: 114.4243, label: '武汉站', zoom: 16 },
          cameraConfig: { center: { lat: 30.6067, lng: 114.4243 }, zoom: 16, duration: 2000, action: 'flyTo' },
          round: 4,
        },
        {
          id: 'event-4-2',
          time: '22:10',
          type: 'critical_event',
          speaker: '市气象局 李局长',
          speakerRole: 'weather-bureau',
          speakerDepartment: '市气象局',
          title: '暴雨红色预警 - 历史极值',
          content: [
            '[22:10] 🔴 **红色预警发布**',
            '',
            '📢 **气象局 李局长** 亲自汇报：',
            '',
            '> "市长！气象数据已突破历史极值！',
            '>',
            '> 🌧 **极端数据**：',
            '> • 12小时累计降雨量：310毫米',
            '> • 最大小时雨强：82毫米/小时',
            '> • 超越2016年7月特大暴雨记录',
            '>',
            '> 🔴 **发布暴雨红色预警！**',
            '>',
            '> 📊 **灾情对比**：',
            '> • 2016年：累计218mm，渍水点162处',
            '> • 2024年（当前）：累计310mm+，渍水点突破200处',
            '>',
            '> ⚠ 建议立即启动I级响应，请求国家防总支援！"',
          ].join('\n'),
          location: { lat: 30.5995, lng: 114.2925, label: '市气象局' },
          isUrgent: true,
          emotion: 'urgent',
          soundEffect: 'alert_red',
          round: 4,
        },
        {
          id: 'event-4-3',
          time: '22:15',
          type: 'escalation',
          speaker: '市长 周先旺',
          speakerRole: 'mayor',
          speakerDepartment: '市人民政府',
          title: 'I级响应启动 - 全城动员',
          content: [
            '[22:15] 🔴 **I级响应启动令**',
            '',
            '📢 **市长 周先旺** 签发最高级别命令：',
            '',
            '> "根据《市防汛抗旱应急预案》，现启动I级应急响应！',
            '>',
            '> 📋 **总动员令**：',
            '> 1. 全市进入防汛紧急最高状态',
            '> 2. 全面停运公共交通（地铁/公交/轮渡/铁路）',
            '> 3. 除应急车辆外，全市车辆禁行',
            '> 4. 全市企事业单位停工停业（除保供单位）',
            '> 5. 请求国家防总派出工作组',
            '>',
            '> 🚨 **部队调用**：',
            '> • 请求中部战区派出解放军支援',
            '> • 武警武汉支队全员出动',
            '> • 民兵预备役动员集结',
            '>',
            '> 🙏 全市人民：生命安全第一，听从指挥，有序转移！"',
          ].join('\n'),
          location: { lat: 30.5872, lng: 114.2985, label: '市应急指挥中心', zoom: 17 },
          cameraConfig: { center: { lat: 30.5872, lng: 114.2985 }, zoom: 17, duration: 1200, action: 'flyTo' },
          isUrgent: true,
          emotion: 'confident',
          round: 4,
        },
        {
          id: 'event-4-4',
          time: '22:30',
          type: 'critical_event',
          speaker: '市应急管理局 张副局长',
          speakerRole: 'emergency-bureau',
          speakerDepartment: '市应急管理局',
          title: '龙王庙险段告急',
          content: [
            '[22:30] 🆘 **龙王庙险段告急**',
            '',
            '📢 **应急管理局 张副局长** 紧急汇报：',
            '',
            '> "市长！龙王庙险段出现险情！',
            '>',
            '> 🌊 **险情详情**：',
            '> • 长江水位：27.80m（超警戒0.50m）',
            '> • 发现渗水点3处',
            '> • 汉江汇流口水流湍急',
            '> • 若溃堤将危及汉口核心区',
            '>',
            '> 🛡 **当前防御**：',
            '> • 武警200人已到达现场加固堤坝',
            '> • 沙袋5000个正在运输中',
            '> • 下游居民正在紧急疏散',
            '>',
            '> ⚠ 需要增派部队和工程机械！刻不容缓！"',
          ].join('\n'),
          location: { lat: 30.579125, lng: 114.291172, label: '龙王庙险段', zoom: 18 },
          cameraConfig: { center: { lat: 30.579125, lng: 114.291172 }, zoom: 18, duration: 2000, action: 'flyTo' },
          isUrgent: true,
          emotion: 'urgent',
          round: 4,
        },
        {
          id: 'event-4-5',
          time: '23:00',
          type: 'response',
          speaker: '武警武汉支队 赵支队长',
          speakerRole: 'armed-police',
          speakerDepartment: '武警武汉支队',
          title: '武装力量驰援到位',
          content: [
            '[23:00] 💪 **国家级救援力量抵达**',
            '',
            '📢 **武警武汉支队 赵支队长** 报告：',
            '',
            '> "市长！武装力量已全面部署：',
            '>',
            '> 🪖 **兵力部署**：',
            '> • 武警武汉支队：800人全员出动',
            '> • 中部战区陆军某旅：1200人驰援',
            '> • 舟桥部队：冲锋舟30艘、架桥设备5套',
            '>',
            '> 🎯 **任务分配**：',
            '> • 龙王庙险段：500人加固堤坝',
            '> • 武昌老城区：600人转移群众',
            '> • 汉口火车站：400人维持秩序',
            '> • 应急预备队：500人机动待命',
            '>',
            '> 🛡 请市长放心，我们坚决守住大堤！"',
          ].join('\n'),
          location: { lat: 30.6067, lng: 114.4243, label: '武警武汉支队', zoom: 15 },
          isUrgent: false,
          emotion: 'confident',
          round: 4,
        },
        {
          id: 'event-4-6',
          time: '23:30',
          type: 'camera_move',
          speaker: '镜头控制',
          title: '镜头拉远至天河机场',
          content: [
            '🎬 **镜头动作**：',
            '',
            '从武汉站 -> 飞越城区至天河机场（Zoom 13）',
            '',
            '📍 **目标位置**：武汉天河国际机场',
            '📐 **坐标**：[114.2211, 30.7737]',
            '🔍 **缩放**：13（大范围航拍机场状态）',
            '',
            '🛫 **画面效果**：机场跑道积水 + 航班大面积延误橙色标识 + 滞留旅客',
          ].join('\n'),
          location: { lat: 30.7737, lng: 114.2211, label: '天河机场', zoom: 13 },
          cameraConfig: { center: { lat: 30.7737, lng: 114.2211 }, zoom: 13, duration: 2000, action: 'panTo' },
          round: 4,
        },
        {
          id: 'event-4-7',
          time: '06-22 00:30',
          type: 'response',
          speaker: '市消防救援支队 孙队长',
          speakerRole: 'fire-brigade',
          speakerDepartment: '市消防救援支队',
          title: '排涝救援战报',
          content: [
            '[00:30] 🚒 **消防救援战报**',
            '',
            '📢 **消防救援支队 孙队长** 报告：',
            '',
            '> "市长！消防救援最新进展：',
            '>',
            '> 🚒 **排涝进展**：',
            '> • 龙吸水泵车2台满负荷运行',
            '> • 移动排涝车5台分散部署',
            '> • 累计抽排积水120万立方米',
            '>',
            '> 🛟 **救援成效**：',
            '> • 冲锋舟20艘全天候作业',
            '> • 累计转移被困群众3500余人',
            '> • 解救被困车辆180余台',
            '>',
            '> ⚠ 但降雨仍在持续，积水面积仍在扩大..."',
          ].join('\n'),
          location: { lat: 30.5798, lng: 114.2599, label: '市消防救援支队' },
          isUrgent: false,
          emotion: 'worried',
          round: 4,
        },
        {
          id: 'event-4-8',
          time: '06-22 06:00',
          type: 'camera_move',
          speaker: '镜头控制',
          title: '黎明俯瞰 — 全市灾后总结',
          content: [
            '🎬 **镜头动作**：',
            '',
            '从天河机场 -> 缓慢拉远至全市俯瞰（Zoom 10.5）',
            '',
            '📍 **目标位置**：武汉市政府（全市总结视角）',
            '📐 **坐标**：[114.305393, 30.599554]',
            '🔍 **缩放**：10.5（俯瞰三镇，长江汉水尽收眼底）',
            '',
            '🌅 **画面效果**：',
            '• 卫星图渐变显示全市积水覆盖范围',
            '• 救援力量蓝色散点分布全城',
            '• 雨量渐弱，云层开始消散',
            '',
            '📊 **24小时灾情汇总**：',
            '• 降雨量：突破320毫米',
            '• 渍水点：超过200处',
            '• 转移群众：超过10万人',
            '• 投入兵力：超过3000人',
            '• 响应等级：IV级 → III级 → II级 → I级',
          ].join('\n'),
          location: { lat: 30.599554, lng: 114.305393, label: '武汉市政府', zoom: 10.5 },
          cameraConfig: { center: { lat: 30.599554, lng: 114.305393 }, zoom: 10.5, duration: 3000, action: 'easeOut' },
          isHighlight: true,
          round: 4,
        },
      ],
    },
  ],
};